# PersistentVolumes para el backend de ADRES
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adres-backend-temp-pv
  labels:
    app: adres-backend
    type: temp
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/adres-backend/temp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adres-backend-wallet-pv
  labels:
    app: adres-backend
    type: wallet
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/adres-backend/wallet
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adres-backend-oci-pv
  labels:
    app: adres-backend
    type: oci
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/adres-backend/oci
