-- Script para crear la tabla de usuarios en Oracle
-- Ejecutar este script en la base de datos Oracle

-- Crear tabla de usuarios
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(60) NOT NULL, -- bcrypt hash (60 caracteres)
    full_name VARCHAR2(100) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL, -- 1 = activo, 0 = inactivo
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Insertar usuario administrador por defecto
-- Contraseña: admin (hash bcrypt generado)
INSERT INTO users (username, email, password_hash, full_name, is_active) 
VALUES (
    'admin', 
    'admin@example.com', 
    '$2b$12$0u4sEwEjgzzAUMMtMMSsSOnXnkLmoYcUgZeAEwth0Qefr62c9OlhW',
    'Administrador del Sistema',
    1
);

-- Insertar algunos usuarios de ejemplo
INSERT INTO users (username, email, password_hash, full_name, is_active) 
VALUES (
    'usuario1', 
    'usuario1@example.com', 
    '$2b$12$0u4sEwEjgzzAUMMtMMSsSOnXnkLmoYcUgZeAEwth0Qefr62c9OlhW', -- password: admin
    'Usuario Ejemplo 1',
    1
);

INSERT INTO users (username, email, password_hash, full_name, is_active) 
VALUES (
    'usuario2', 
    'usuario2@example.com', 
    '$2b$12$0u4sEwEjgzzAUMMtMMSsSOnXnkLmoYcUgZeAEwth0Qefr62c9OlhW', -- password: admin
    'Usuario Ejemplo 2',
    1
);

-- Confirmar los cambios
COMMIT;